#!/bin/bash
set -euo pipefail

# =============================================================================
# DAESC-P2.sh - Individual Pipeline: Recombine FASTQ → CellRanger → SALSA
# =============================================================================
# Purpose:
#   Complete processing pipeline for a single individual:
#   Phase 1: Merge split FASTQ.gz files from multiple SRR runs
#   Phase 2: Run CellRanger count for gene expression quantification
#   Phase 3: Run SALSA pipeline for allele-specific expression analysis
#
# Usage: 
#   bash DAESC-P2.sh root_path=... individual_id=... chr_list=...
#
# Example: 
#   bash DAESC-P2.sh root_path=/scratch/user/tfcui2025/DAESC/mypipeline_2 individual_id=12345678 chr_list="1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22"
#
# Input:
#   - Split FASTQ.gz files from DAESC-P1: Data_SRR/*/split_fastq/*_Ind{individual}_*.fastq.gz
#   - Per-individual barcode file: cellbarcodes/{individual}.csv
#
# Output:
#   - Merged FASTQ.gz files: Data_Individuals/{individual}/Ind{individual}_S1_*.fastq.gz
#   - CellRanger output: Data_Individuals/{individual}/Ind{individual}/outs/
#   - SALSA ASE counts: Data_Individuals/{individual}/{individual}_step7/
#
# Dependencies:
#   - CellRanger (tested with v9.0.1)
#   - Singularity with SALSA container
#   - Reference genome (GRCh38)
#   - SHAPEIT5 phasing reference panel
#   - GATK resources (funcotator data sources)
# =============================================================================

# ============================================================================
# Argument Parsing
# ============================================================================
root_path=""
individual_id=""
chr_list=""

for ARG in "$@"; do
    case $ARG in
        root_path=*) root_path="${ARG#*=}" ;;
        individual_id=*) individual_id="${ARG#*=}" ;;
        chr_list=*) chr_list="${ARG#*=}" ;;
        *) echo "❌ Unknown argument: $ARG"; exit 1 ;;
    esac
done

# Argument Validation
if [[ -z "$root_path" || -z "$individual_id" || -z "$chr_list" ]]; then
    echo "❌ Usage: $0 root_path=... individual_id=... chr_list=..."
    echo "   Example: $0 root_path=/scratch/user/tfcui2025/DAESC/mypipeline_2 individual_id=12345678 chr_list=\"1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22\""
    exit 1
fi

Individual_ID="$individual_id"
CHR_STRING="$chr_list"

# ============================================================================
# Path Configuration
# ============================================================================
ROOT_PATH="$root_path"
REFERENCE_PATH="${ROOT_PATH}/reference_test"
CELLRANGER_PATH="${REFERENCE_PATH}/cellranger-9.0.1"
SIF_PATH="${REFERENCE_PATH}/salsa_latest.sif"
BARCODE_DIR="${ROOT_PATH}/cellbarcodes"

# Data directories
DATA_SRR_DIR="${ROOT_PATH}/Data_SRR"
DATA_INDIV_DIR="${ROOT_PATH}/Data_Individuals"

# Individual-specific paths
INDIV_DIR="${DATA_INDIV_DIR}/${Individual_ID}"
OUTPUT_DIR_BASE="${INDIV_DIR}"
LOG_DIR="${INDIV_DIR}/logs"
SCRATCH1="${INDIV_DIR}/scratch"

# ============================================================================
# Initialization
# ============================================================================
echo "╔══════════════════════════════════════════════════════════════════════╗"
echo "║              Individual Pipeline Started                             ║"
echo "╚══════════════════════════════════════════════════════════════════════╝"
echo ""
echo "Individual ID: ${Individual_ID}"
echo "Chromosomes: ${CHR_STRING}"
echo "Root Path: ${ROOT_PATH}"
echo "Start Time: $(date)"
echo ""

# Create required directories
mkdir -p "${INDIV_DIR}" "${LOG_DIR}" "${SCRATCH1}"

# ============================================================================
# Phase 1: Recombine FASTQ.gz Files
# ============================================================================
# Merge split FASTQ.gz files from multiple SRR runs into single files per read type
# This step collects all per-individual FASTQ.gz files generated by DAESC-P1
echo "═══════════════════════════════════════════════════════════════════════"
echo "Phase 1: Recombine FASTQ.gz files"
echo "═══════════════════════════════════════════════════════════════════════"

phase1_start=$(date +%s)
 
#for read_type in R1 R2; do
#    output_file="${INDIV_DIR}/Ind${Individual_ID}_S1_${read_type}_001.fastq.gz"
#    > "$output_file"
    
#    echo "🔄 Merging ${read_type} files for Individual ${Individual_ID}..."
    
    # Find and merge all matching FASTQ.gz files
    # File location: Data_SRR/{SRR_ID}/split_fastq/
    # File naming: {SRR_ID}_Ind{Individual_ID}_{read_type}_001.fastq.gz
    # Note: gzip files can be concatenated directly with cat
#    file_count=0
#    while IFS= read -r -d '' file; do
#        echo "  📎 Adding: $(basename $file)"
#        cat "$file" >> "$output_file"
#        file_count=$((file_count + 1))
#    done < <(find "${DATA_SRR_DIR}" -type f -path "*/split_fastq/*" -name "*_Ind${Individual_ID}_${read_type}_001.fastq.gz" -print0 2>/dev/null | sort -z)
    
#    if [[ $file_count -eq 0 ]]; then
#        echo "  ⚠️ Warning: No ${read_type} files found for Individual ${Individual_ID}"
#        echo "     Expected location: ${DATA_SRR_DIR}/*/split_fastq/*_Ind${Individual_ID}_${read_type}_001.fastq.gz"
#    else
#        # Count total reads in merged compressed file
#        read_count=$(($(zcat "$output_file" | wc -l) / 4))
#        echo "  ✅ Merged ${file_count} files → ${output_file}"
#        echo "     Total reads: ${read_count}"
#    fi
#done

phase1_end=$(date +%s)
echo ""
echo "📊 Phase 1 Summary:"
ls -lh "${INDIV_DIR}"/Ind${Individual_ID}_S1_*.fastq.gz 2>/dev/null || echo "   No files generated!"
echo ""
echo "✅ Phase 1 completed in $((phase1_end - phase1_start)) seconds"
echo ""

# ============================================================================
# Phase 2: CellRanger Count
# ============================================================================
# Run CellRanger count to align reads and quantify gene expression
# Output: BAM file with aligned reads and feature-barcode matrices
# Note: CellRanger natively supports FASTQ.gz files
echo "═══════════════════════════════════════════════════════════════════════"
echo "Phase 2: CellRanger Count"
echo "═══════════════════════════════════════════════════════════════════════"

phase2_start=$(date +%s)

# Verify CellRanger installation
if [[ ! -x "${CELLRANGER_PATH}/cellranger" ]]; then
    echo "❌ CellRanger not found at: ${CELLRANGER_PATH}/cellranger"
    exit 1
fi

# Verify reference genome
if [[ ! -d "${REFERENCE_PATH}/refdata-gex-GRCh38-2020-A" ]]; then
    echo "❌ Reference data not found at: ${REFERENCE_PATH}/refdata-gex-GRCh38-2020-A"
    exit 1
fi

SAMPLE_NAME="Ind${Individual_ID}"
FASTQ_DIR="${INDIV_DIR}"
CELLRANGER_LOG="${LOG_DIR}/cellranger_${SAMPLE_NAME}.log"

# Get resource parameters from SLURM environment (handle units if present)
CORES="${SLURM_CPUS_PER_TASK:-8}"
# Extract numeric value from SLURM_MEM_PER_NODE (remove G/M units)
if [[ -n "${SLURM_MEM_PER_NODE:-}" ]]; then
    MEM=$(echo "${SLURM_MEM_PER_NODE}" | sed 's/[^0-9]//g')
    # Convert MB to GB if original unit was M
    if [[ "${SLURM_MEM_PER_NODE}" == *"M"* ]]; then
        MEM=$((MEM / 1024))
    fi
else
    MEM=64
fi

echo "🧬 Running CellRanger for: ${Individual_ID}"
echo "📁 FASTQ directory: ${FASTQ_DIR}"
echo "📦 Sample name: ${SAMPLE_NAME}"
echo "📚 Reference: ${REFERENCE_PATH}/refdata-gex-GRCh38-2020-A"
echo "💻 Resources: ${CORES} cores, ${MEM} GB memory"
echo "📝 Log file: ${CELLRANGER_LOG}"

cd "${INDIV_DIR}"

# Check if CellRanger was already run (skip to save time)
if [[ -f "${INDIV_DIR}/${SAMPLE_NAME}/outs/possorted_genome_bam.bam" ]]; then
    echo "⏭️  CellRanger output already exists, skipping..."
else
    # CellRanger natively supports FASTQ.gz input files
    "${CELLRANGER_PATH}/cellranger" count \
        --id="${SAMPLE_NAME}" \
        --transcriptome="${REFERENCE_PATH}/refdata-gex-GRCh38-2020-A" \
        --fastqs="${FASTQ_DIR}" \
        --sample="${SAMPLE_NAME}" \
        --create-bam=true \
        --localcores="${CORES}" \
        --localmem="${MEM}" \
        --nosecondary \
        &> "${CELLRANGER_LOG}"
    
    # Verify CellRanger completed successfully
    if [[ ! -f "${INDIV_DIR}/${SAMPLE_NAME}/outs/possorted_genome_bam.bam" ]]; then
        echo "❌ CellRanger failed! Check log: ${CELLRANGER_LOG}"
        exit 1
    fi
fi

phase2_end=$(date +%s)
echo ""
echo "✅ Phase 2 completed in $((phase2_end - phase2_start)) seconds"
echo ""

# ============================================================================
# Phase 3: SALSA Analysis (in Singularity container)
# ============================================================================
# Run SALSA pipeline for allele-specific expression analysis
# Steps: Genotype → Phase → Annotate → Filter → WASP → ASE Count
echo "═══════════════════════════════════════════════════════════════════════"
echo "Phase 3: SALSA Analysis"
echo "═══════════════════════════════════════════════════════════════════════"

phase3_start=$(date +%s)

# Verify Singularity container exists
echo "🔍 Checking prerequisites..."
if [[ ! -f "$SIF_PATH" ]]; then
    echo "❌ Error: SIF file not found: $SIF_PATH"
    exit 1
fi
echo "  ✅ SIF file: $SIF_PATH"

# Verify CellRanger BAM file exists
INPUT_BAM="${INDIV_DIR}/Ind${Individual_ID}/outs/possorted_genome_bam.bam"
if [[ ! -f "$INPUT_BAM" ]]; then
    echo "❌ Error: BAM file not found: $INPUT_BAM"
    echo "   CellRanger may have failed. Check log: ${CELLRANGER_LOG}"
    exit 1
fi
echo "  ✅ BAM file: $INPUT_BAM"

# Verify per-individual barcode file exists
BARCODE_FILE="${BARCODE_DIR}/${Individual_ID}.csv"
if [[ ! -f "$BARCODE_FILE" ]]; then
    echo "❌ Error: Barcode file not found: $BARCODE_FILE"
    exit 1
fi
echo "  ✅ Barcode file: $BARCODE_FILE"

echo ""
echo "📁 Directory Setup:"
echo "   Output: $OUTPUT_DIR_BASE"
echo "   Logs: $LOG_DIR"
echo "   Scratch: $SCRATCH1"
echo "   Barcodes: $BARCODE_DIR"
echo ""

echo "🐋 Starting SALSA analysis in Singularity container..."
echo ""

# Parse chromosome list into array
IFS=' ' read -r -a CHR_LIST <<< "$CHR_STRING"

for CHR in "${CHR_LIST[@]}"; do
    echo "═══════════════════════════════════════════════════════════════════════"
    echo "Processing chr${CHR} for individual ${Individual_ID}"
    echo "═══════════════════════════════════════════════════════════════════════"
    
    CHR_LOG="${LOG_DIR}/${Individual_ID}_chr${CHR}.log"
    > "$CHR_LOG"  # Clear log file for this chromosome
    
    # ========================================================================
    # Step 1: Genotype Calling
    # ========================================================================
    # Call variants from RNA-seq data using GATK HaplotypeCaller
    echo "  [1/6] Genotyping..."
#    singularity exec \
#        --bind ${ROOT_PATH}:${ROOT_PATH} \
#        --env SCRATCH1="${SCRATCH1}" \
#        "${SIF_PATH}" \
#        bash ${ROOT_PATH}/scr/salsa1_gatk_genotype.sh \
#            -i ${INPUT_BAM} \
#            -n ${Individual_ID} \
#            -r ${REFERENCE_PATH}/refdata-gex-GRCh38-2020-A \
#            -g ${REFERENCE_PATH}/gatk \
#            -d ${OUTPUT_DIR_BASE}/${Individual_ID}_step1 \
#            -o ${Individual_ID}.rna.chr${CHR}.vcf.gz \
#            -l chr${CHR} \
#            -m rna \
#            --threads 5 >> ${CHR_LOG} 2>&1
    echo "        ✅ Genotyping done"

    # ========================================================================
    # Step 1b: VCF Filtering
    # ========================================================================
    # Filter variants: GQ>=30, SNVs only (single nucleotide variants)
    echo "  [1b/6] Filtering VCF..."
#    singularity exec \
#        --bind ${ROOT_PATH}:${ROOT_PATH} \
#        --env SCRATCH1="${SCRATCH1}" \
#        "${SIF_PATH}" \
#        bcftools view -i 'FORMAT/GQ>=30 && strlen(REF)=1 && strlen(ALT)=1' \
#            ${OUTPUT_DIR_BASE}/${Individual_ID}_step1/${Individual_ID}.rna.chr${CHR}.vcf.gz \
#            -Oz -o ${OUTPUT_DIR_BASE}/${Individual_ID}_step1/filtered_${Individual_ID}.rna.chr${CHR}.vcf.gz >> ${CHR_LOG} 2>&1
    
    # Index filtered VCF
#    singularity exec \
#        --bind ${ROOT_PATH}:${ROOT_PATH} \
#        --env SCRATCH1="${SCRATCH1}" \
#        "${SIF_PATH}" \
#        bcftools index -t ${OUTPUT_DIR_BASE}/${Individual_ID}_step1/filtered_${Individual_ID}.rna.chr${CHR}.vcf.gz >> ${CHR_LOG} 2>&1
    echo "        ✅ VCF filtering done"

    # ========================================================================
    # Step 2: Haplotype Phasing
    # ========================================================================
    # Phase variants using SHAPEIT5 reference panel
    echo "  [2/6] Phasing..."
#    singularity exec \
#        --bind ${ROOT_PATH}:${ROOT_PATH} \
#        --env SCRATCH1="${SCRATCH1}" \
#        "${SIF_PATH}" \
#        bash ${ROOT_PATH}/scr/salsa2_phase_vcf_shapeit5.sh \
#            --library_id pbmc_1k \
#            --inputvcf ${OUTPUT_DIR_BASE}/${Individual_ID}_step1/filtered_${Individual_ID}.rna.chr${CHR}.vcf.gz \
#            --outputdir ${OUTPUT_DIR_BASE}/${Individual_ID}_step3 \
#            --outputvcf pipe3_${Individual_ID}.pass.rna.chr${CHR}hcphase.vcf.gz \
#            --phasingref ${REFERENCE_PATH} \
#            --interval chr${CHR} \
#            --hcphase \
#            --snvonly \
#            --verbose \
#            --threads 5 >> ${CHR_LOG} 2>&1
    echo "        ✅ Phasing done"

    # ========================================================================
    # Step 3: Functional Annotation
    # ========================================================================
    # Annotate variants with gene information using GATK Funcotator
    echo "  [3/6] Annotation..."
#    singularity exec \
#        --bind ${ROOT_PATH}:${ROOT_PATH} \
#        --env SCRATCH1="${SCRATCH1}" \
#        "${SIF_PATH}" \
#        bash ${ROOT_PATH}/scr/salsa3_gatk_anno_vcf.sh \
#            --library_id pbmc_1k \
#            --inputvcf ${OUTPUT_DIR_BASE}/${Individual_ID}_step3/pipe3_${Individual_ID}.pass.rna.chr${CHR}hcphase.vcf.gz \
#            --outputdir ${OUTPUT_DIR_BASE}/${Individual_ID}_step4 \
#            --outputvcf pipe3_${Individual_ID}.pass.rna.chr${CHR}hcphase.funco.vcf.gz \
#            --reference ${REFERENCE_PATH}/refdata-gex-GRCh38-2020-A \
#            --funcotation ${REFERENCE_PATH}/funcotator_dataSources.v1.6.20190124g \
#            --output_table pipe3_${Individual_ID}.pass.rna.chr${CHR}hcphase.formatted.csv \
#            --modality rna \
#            --threads 5 >> ${CHR_LOG} 2>&1
    echo "        ✅ Annotation done"

    # ========================================================================
    # Step 4: Barcode Filtering
    # ========================================================================
    # Filter BAM to retain only reads from valid cell barcodes
    echo "  [4/6] Barcode filtering..."
    singularity exec \
        --bind ${ROOT_PATH}:${ROOT_PATH} \
        --env SCRATCH1="${SCRATCH1}" \
        "${SIF_PATH}" \
        bash ${ROOT_PATH}/scr/salsa4_filterbam.sh \
            --library_id pbmc_1k \
            --validate \
            --inputbam ${INPUT_BAM} \
            --modality rna \
            --interval chr${CHR} \
            --barcodes ${BARCODE_FILE} \
            --outputdir ${OUTPUT_DIR_BASE}/${Individual_ID}_step5 \
            --outputbam pbmc_1k_${Individual_ID}.bcfilter.chr${CHR}.bam \
            --threads 5 >> ${CHR_LOG} 2>&1
    echo "        ✅ Barcode filtering done"

    # ========================================================================
    # Step 5: WASP Filtering
    # ========================================================================
    # Apply WASP method to remove mapping bias at heterozygous sites
    echo "  [5/6] WASP..."
    singularity exec \
        --bind ${ROOT_PATH}:${ROOT_PATH} \
        --env SCRATCH1="${SCRATCH1}" \
        "${SIF_PATH}" \
        bash ${ROOT_PATH}/scr/salsa5_wasp.sh \
            --inputvcf ${OUTPUT_DIR_BASE}/${Individual_ID}_step4/pipe3_${Individual_ID}.pass.rna.chr${CHR}hcphase.funco.vcf.gz \
            --inputbam ${OUTPUT_DIR_BASE}/${Individual_ID}_step5/pbmc_1k_${Individual_ID}.bcfilter.chr${CHR}.bam \
            --outputdir ${OUTPUT_DIR_BASE}/${Individual_ID}_step6 \
            --outputbam pbmc_1k_${Individual_ID}.hcphase.chr${CHR}wasp.bam \
            --genotype rna \
            --stargenome ${REFERENCE_PATH}/refdata-gex-GRCh38-2020-A/star \
            --chromInfo ${REFERENCE_PATH}/hg38_chromInfo.txt.gz \
            --library_id pbmc_1k \
            --modality rna \
            --isphased \
            --interval chr${CHR} \
            --threads 5 >> ${CHR_LOG} 2>&1
    echo "        ✅ WASP done"

    # ========================================================================
    # Step 6: Allele-Specific Expression Counting
    # ========================================================================
    # Count reads supporting reference vs alternative alleles at heterozygous sites
    # Generates pseudobulk, single-cell, and cell-type level ASE counts
    echo "  [6/6] Allele-specific counting..."
    singularity exec \
        --bind ${ROOT_PATH}:${ROOT_PATH} \
        --env SCRATCH1="${SCRATCH1}" \
        "${SIF_PATH}" \
        bash ${ROOT_PATH}/scr/salsa6_gatk_alleleCount.sh \
            --inputvcf ${OUTPUT_DIR_BASE}/${Individual_ID}_step4/pipe3_${Individual_ID}.pass.rna.chr${CHR}hcphase.funco.vcf.gz \
            --inputbam ${OUTPUT_DIR_BASE}/${Individual_ID}_step6/pbmc_1k_${Individual_ID}.hcphase.chr${CHR}wasp.bam \
            --outputdir ${OUTPUT_DIR_BASE}/${Individual_ID}_step7 \
            --barcodes ${BARCODE_FILE} \
            --genotype rna_genotype \
            --library_id pbmc_1k \
            --modality rna \
            --reference ${REFERENCE_PATH}/refdata-gex-GRCh38-2020-A \
            --pseudobulk_counts \
            --single_cell_counts \
            --celltype_counts \
            --interval chr${CHR} \
            --isphased \
            --threads 5 >> ${CHR_LOG} 2>&1
    echo "        ✅ Allele-specific counting done"

    echo ""
    echo "  ✅ chr${CHR} completed!"
    echo ""
done

phase3_end=$(date +%s)
echo ""
echo "✅ Phase 3 completed in $((phase3_end - phase3_start)) seconds"
echo ""

# ============================================================================
# Pipeline Completion Summary
# ============================================================================
total_time=$((phase3_end - phase1_start))

echo "╔══════════════════════════════════════════════════════════════════════╗"
echo "║              Individual Pipeline Completed                           ║"
echo "╚══════════════════════════════════════════════════════════════════════╝"
echo ""
echo "Individual: ${Individual_ID}"
echo "Total Time: ${total_time} seconds ($((total_time / 60)) minutes)"
echo "Output Directory: ${OUTPUT_DIR_BASE}"
echo "End Time: $(date)"
echo ""
echo "Output locations:"
echo "  - Merged FASTQ.gz: ${INDIV_DIR}/Ind${Individual_ID}_S1_*.fastq.gz"
echo "  - CellRanger BAM: ${INPUT_BAM}"
echo "  - scASE counts: ${OUTPUT_DIR_BASE}/${Individual_ID}_step7/"
echo ""